class:
    - {name: "\\ModulesGarden\\ProductCrossSelling\\Core\\Http\\Request", method: "build",                        args: []}
    - {name: '\\ModulesGarden\\ProductCrossSelling\\Core\\Http\\View\\Smarty',  method: "get",                    args: [NULL,NULL]}
    - {name: '\\ModulesGarden\\ProductCrossSelling\\Core\\HandlerError\\Logger',  method: "get",                  args: ["default","debug.log","warning.log","error.log"]}
    - {name: '\\ModulesGarden\\ProductCrossSelling\\Core\\RegisterManager\\Register',  method: "getInstace",      args: []}
